;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        end-of-visual-line
        indent-for-tab-command
        org-self-insert-command
        smart-hungry-delete-backward-char
        smart-hungry-delete-forward-char
        wgrep-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        iedit-switch-to-mc-mode
        ))
