;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        smart-hungry-delete-backward-char
        smart-hungry-delete-forward-char
        ))

(setq mc/cmds-to-run-once
      '(
        iedit-switch-to-mc-mode
        ))
