sudo: true
dist: xenial
language: generic

install:
  - sudo apt-get install emacs
  - emacs --version

script:
  - emacs --batch -l test.el
  - mv config.html index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  verbose: true
  deployment_file: true
  on:
    branch: master
