language: generic

env:
  global:
    - CURL="wget"
  matrix:
    - EMACS_VERSION=27.1
    - EMACS_VERSION=master

matrix:
  allow_failures:
    - env: EMACS_VERSION=master

install:
  - $CURL https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $EMACS --version

script:
  - sh emacs-pkg-install.sh htmlize  
  - mv config.html index.html
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  verbose: true
  deployment_file: true
  on:
    branch: master
