sudo: true
dist: xenial
language: generic

install:
  - wget https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-27.1.tar.gz
  - tar -xaf emacs-bin-27.1.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $EMACS --version

script:
  - $EMACS --batch -l build-gh-pages.el
  - mv config.html index.html
  - rm -rf .packages/ && rm .mc-lists.el && rm -v !("index.html"|"dotfiles.html")

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  verbose: true
  deployment_file: true
  on:
    branch: master
