sudo: true
dist: xenial
language: generic

install:
  - sudo apt-get update
  - wget https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-27.1.tar.gz
  - tar -xaf emacs-bin-27.1.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $EMACS --version
  - sudo apt-get install emacs-goodies-el

script:
  - emacs config.org --batch -f org-html-export-to-html
  - mv config.html index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  verbose: true
  deployment_file: true
  on:
    branch: master
