sudo: true
dist: xenial
language: generic

env:
  global:
    - CURL="wget"
  matrix:
    - EMACS_VERSION=27.1
    - EMACS_VERSION=master

matrix:
  allow_failures:
    - env: EMACS_VERSION=master

install:
  - sudo apt-get update
  - sudo apt-get install emacs
  - sudo apt-get install emacs-goodies-el

script:
  - emacs config.org --batch -f org-html-export-to-html
  - mv config.html index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  verbose: true
  deployment_file: true
  on:
    branch: master
