;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        end-of-visual-line
        org-beginning-of-line
        org-end-of-line
        org-force-self-insert
        ))

(setq mc/cmds-to-run-once
      '(
        kill-region
        mouse-set-secondary
        org-self-insert-command
        smart-hungry-delete-backward-char
        smart-hungry-delete-forward-char
        ))
